version: 0.2

phases:
  install:
    commands:
      - echo Installing nodejs...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
      - echo Installing yarn...
      - npm install --global yarn
    pre_build:
      commands:
        - Installing dependencies
        - yarn
    build:
      commands:
        - echo Testing...
        - npm run test
        - echo Building...
        - npm run build
  
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist