version: 0.2

phases:
  install:
    commands:
      - echo Installing nodejs...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
    pre_build:
      commands:
      - echo Nothing to do in the pre_build phase...
    build:
      commands:
      - npm install
      - npm run build
    post_build:
      commands:
      - echo Build completed on
  
artifacts:
  files:
    - "**/*"
  discard-path: no
  base-directory: build